service:
  name: armada

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  profile: codefantry
  runtime: nodejs10.x
  region: ap-southeast-1

functions:
  status:
    handler: handler.status
    events:
      - http:
          method: get
          path: status
