service:
  name: armada

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  profile: codefantry
  runtime: nodejs10.x
  region: ap-southeast-1
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiRootResourceId

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  list:
    handler: handler.list
    events:
      - http:
          method: get
          # path: add-your-path-here
