service:
  name: armada

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  environment:
    APP_SECRET: ${ssm:APP_SECRET_${self:custom.stage}}
    CLIENT_ID: ${ssm:client_id_${self:custom.stage}}
    CLIENT_SECRET: ${ssm:client_secret_${self:custom.stage}}
    NODE_ENV: ${self:custom.stage}
    NOTIFICATIONS_URI: ${ssm:notifications_uri}
    PGDATABASE: ${ssm:dbname_${self:custom.stage}}
    PGHOST: ${ssm:dbhost_${self:custom.stage}}
    PGPASSWORD: ${ssm:dbpass_${self:custom.stage}}
    PGPORT: ${ssm:dbport_${self:custom.stage}}
    PGUSER: ${ssm:dbuser_${self:custom.stage}}
  runtime: nodejs10.x
  region: ap-southeast-1
  stackName: ${self:custom.stage}-<service name here>
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
      Resource: "arn:aws:ssm:ap-southeast-1:#{AWS::AccountId}:parameter/*"
  apiGateway:
    restApiId:
      "Fn::ImportValue": armada-${self:custom.stage}-api-id
    restApiRootResourceId:
      "Fn::ImportValue": armada-${self:custom.stage}-api-root-id

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  index:
    handler: handler.index
    events:
      - http:
          method: get
          cors: true
          path: index
  create:
    handler: handler.create
    events:
      - http:
          method: post
          cors:
            origin: "*" # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - kasl-key
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          path: enter-post-path
  list:
    handler: handler.list
    events:
      - http:
          method: get
          cors:
            origin: "*" # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - kasl-key
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          path: enter-get-path
