version: '3.7'

services:
  armada:
    build:
      context: .
      target: dev
    command: ['npm', 'start']
    container_name: 'armada'
    env_file: './.env'
    ports:
      - '8880:8888'
    restart: unless-stopped
    volumes:
      - ./.git:/app/.git:ro
      - ./src:/app/src
      - ../coverages/armada:/app/coverage
      - ./jest.config.js:/app/jest.config.js
      - ./jest-coverage.config.js:/app/jest-coverage.config.js
      - ./nodemon.json:/app/nodemon.json
      - ./package.json:/app/package.json
networks:
  default:
    name: ksl-network
