version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # install
      - docker build --no-cache --target essentials -t katmoni-armada .
  pre_build:
    commands:
      # linter
      - docker run --rm katmoni-armada npm run l
  build:
    commands:
      # test
      - docker run --rm katmoni-armada npm run coverage
