version: 0.2

env:
  parameter-store:
    AWS_DEFAULT_REGION: 'DEFAULT_REGION'
    AWS_ACCESS_KEY_ID: 'ACCESS_KEY_ID'
    AWS_SECRET_ACCESS_KEY: 'SECRET_ACCESS_KEY'

phases:
  build:
    commands:
      - echo 'STAGE=integration' >.env
      - echo 'AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION' >> .env
      - echo 'AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID >> .env
      - echo 'AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY >> .env
      - sh .pipeline/loop-services.sh
