service:
  name: alfred

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  environment:
    APP_SECRET: ${ssm:app-secret-${self:custom.stage}}
    CLIENT_ID: ${ssm:client-id-${self:custom.stage}}
    CLIENT_SECRET: ${ssm:client-secret-${self:custom.stage}}
    NODE_ENV: ${self:custom.stage}
    NOTIFICATIONS_URI: ${ssm:notifications-uri}
    PGDATABASE: ${ssm:dbname-${self:custom.stage}}
    PGPASSWORD: ${ssm:dbpass-${self:custom.stage}}
    PGPORT: ${ssm:dbport-${self:custom.stage}}
    PGHOST: ${ssm:dbhost-${self:custom.stage}}
    PGUSER: ${ssm:dbuser-${self:custom.stage}}
  runtime: nodejs10.x
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ssm:GetParameters'
      Resource: 'arn:aws:ssm:ap-southeast-1:#{AWS::AccountId}:parameter/*'
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiRootResourceId

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  oauth:
    handler: handler.oauth
    environment:
      APP_SECRET: ${ssm:APP_SECRET_${self:custom.stage}}
    events:
      - http:
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - kasl-key
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          path: alfred
