service:
  name: general

plugins:
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  apiName: armada-${self:custom.stage}

functions:
  sitrep:
    handler: handler.sitrep
    events:
      - http:
          method: get
          path: sitrep

custom:
  stage: ${opt:stage, self:provider.stage}

resources:
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: armada-${self:custom.stage}-api-id

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: armada-${self:custom.stage}-api-root-id
