service:
  name: general

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  profile: armada
  runtime: nodejs10.x
  region: ap-southeast-1

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  sitrep:
    handler: handler.sitrep
    events:
      - http:
          method: get
          path: sitrep

resources:
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:custom.stage}-ApiGatewayRestApiId

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${self:custom.stage}-ApiGatewayRestApiRootResourceId
