service:
  name: katmoni

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  environment:
    APP_SECRET: ${ssm:APP_SECRET_${self:custom.stage}}
    NODE_ENV: ${self:custom.stage}
    DATABASE_NAME: ${ssm:dbname_${self:custom.stage}}
    DATABASE_PASSWORD: ${ssm:dbpass_${self:custom.stage}}
    DATABASE_PORT: ${ssm:dbport_${self:custom.stage}}
    DATABASE_HOST: ${ssm:dbhost_${self:custom.stage}}
    DATABASE_USER: ${ssm:dbuser_${self:custom.stage}}
  runtime: nodejs10.x
  region: ap-southeast-1
  stackName: ${self:custom.project}-${self:custom.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
      Resource: "arn:aws:ssm:ap-southeast-1:#{AWS::AccountId}:parameter/*"

custom:
  stage: ${opt:stage, self:provider.stage}
  project: katmoni

functions:
  sitrep:
    handler: handler.sitrep
    events:
      - http:
          method: get
          cors: true
          path: sitrep

resources:
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:custom.project}-${self:custom.stage}-api-id

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${self:custom.project}-${self:custom.stage}-api-root-id
